### ISSUE TITLE
UniqueViolationError parsing: Error detail with postgres role

### ISSUE THREAD

**Issue by NelsonFrancisco** [Vincit/db-errors#18]
As you can check in [this](https://stackoverflow.com/questions/55373612/not-getting-detail-section-of-unique-constraint-error-when-row-level-security) StackOverflow discussion, error details can be omited from the error depending on the role of the connected user.

I notice this because I have tests in my API. When I changed the main knex connection to use another role, some tests started failing, one of them required that the returned error was 'UniqueViolationError'.

With a little investigation, I notice that the 'nativeError' in the returned error had no details. More search led me into that StackOverflow thread.

In your 'UniqueViolationError' parser you have:

```js
const colsMatch = UNIQUE_COLUMNS_REGEX.exec(err.detail);

if (!colsMatch) {
    return null;
}
```

Well, we can see now why the returned error is not correctly parsed. I get a plain 'ConstraintViolationError' only because the error detail is not correctly parsed (the details comes 'undefined', because of this new role)

I believe this is conceptually wrong: it still is a UniqueViolationError. It still has the same code. Postgres database does tell you that it is a UniqueViolationError.

So, I believe a better solution would be to parse the error anyway without returning the columns information. This would have to be correctly documented, of course.

Thanks

**Comment by FaustTheFirst** [comment]
Same thing, instead of triggering **UniqueViolationError** I have **ConstraintViolationError**. Hope it will be fixed in the near future

**Comment by koskimas** [comment]
I hope you fix it yourselves and provide aPR.

**Comment by FaustTheFirst** [comment]
Hmm, in fact, I can try to do this

**Comment by koskimas** [comment]
Could you at least provide the error that causes this failure? Like the string that's incorrectly parsed? The correct solution is to fix the parsing and not add a hack that falls back to undefined fields.

**Comment by koskimas** [comment]
Will be fixed in the next release.
