### ISSUE TITLE
Some errors leaking through without being wrapped by a specific type

### ISSUE THREAD

**Issue by npearson72** [Vincit/db-errors#26]
When passing `undefined` or `null` to `.findById` in objection, I'm seeing the following error:

```
Error: undefined was passed to findById
    at assertIdNotUndefined (/Users/me/Dev/personal/playground/todos/api/express/node_modules/objection/lib/utils/assert.js:18:11)
```

Would be nice if this was caught by a `NotFoundError`

Note: Using a `.throwIfNotFound` call mitigates when `null` is passed into `.findById`, but not `undefined`.

Using PostgreSQL

**Comment by koskimas** [comment]
That error doesn't come from the DB. Objection throws it before the query is executed.

**Comment by npearson72** [comment]
So it's an ORM error. Do you have a recommendation on how to handle it? Would be nice if it was typed.

**Comment by koskimas** [comment]
It's a programming error if you pass an undefined value. You should handle it by fixing the bug.

**Comment by npearson72** [comment]
Good advice. Thanks.
