### ISSUE TITLE
publish with TypeScript definitions

### ISSUE THREAD

**Issue by restjohn** [Vincit/db-errors#5]
Is there any chance you might publish the NPM package with TypeScript definitions bundled?

**Comment by koskimas** [comment]
Yep, I'm making a new release today.

**Comment by koskimas** [comment]
Ok, I just realized that the MSSQL support that was just added doesn't run tests on travis. We need to take care of that before I can release.

**Comment by restjohn** [comment]
Great, thanks!

**Comment by koskimas** [comment]
version 0.2.0 has been released.

**Comment by restjohn** [comment]
Thanks for the quick response.
