### ISSUE TITLE
ForeignKeyViolationError fails on mysql db when constraint has ON DELETE

### ISSUE THREAD

**Issue by jatj** [Vincit/db-errors#7]
Parsing the sqlMessage when a constraint fails that has ON DELETE or ON UPDATE properties fails. So it doesnt recognize the error and throws a normal _ConstraintViolationError_, instead of the _ForeignKeyViolationError_ . 

Example of the sqlMessage when the regex fails: 

```
"Cannot add or update a child row: a foreign key constraint fails (`conecta_pyme_calendar`.`event`, CONSTRAINT `event_fkuser_foreign` FOREIGN KEY (`fkUser`) REFERENCES `User` (`idUser`) ON DELETE CASCADE)".
```

This can be easily fixed by changing the actual regex:

 ```const NO_REFERENCED_REGEX = /a foreign key constraint fails \(`(.+)`\.`(.+)`, CONSTRAINT `(.+)` FOREIGN KEY \(`(.+)`\) REFERENCES `(.+)` \(`(.+)`\)\)/;```

to: 

 ```const NO_REFERENCED_REGEX = /a foreign key constraint fails \(`(.+)`\.`(.+)`, CONSTRAINT `(.+)` FOREIGN KEY \(`(.+)`\) REFERENCES `(.+)` \(`(.+)`\)/;```

Just delete the last parenthesis from the regex.

**Comment by koskimas** [comment]
Thanks for the report. I'll fix this soon.

**Comment by koskimas** [comment]
@jatj 0.2.2 has been released.

**Comment by jatj** [comment]
Cool, thanks
